# syntax=docker/dockerfile:1

FROM node:20-alpine as base
WORKDIR /app
ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=1
ENV WATCHPACK_POLLING=true

# Dev runtime
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=1
ENV WATCHPACK_POLLING=true
COPY package*.json ./
RUN npm install
EXPOSE 3000
CMD ["npm", "run", "start:dev"] 